// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: contract.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorType int32

const (
	AuthErrorType_AuthErrorTypeNone           AuthErrorType = 0
	AuthErrorType_AuthErrorTypeUserWrongCreds AuthErrorType = 1
)

// Enum value maps for AuthErrorType.
var (
	AuthErrorType_name = map[int32]string{
		0: "AuthErrorTypeNone",
		1: "AuthErrorTypeUserWrongCreds",
	}
	AuthErrorType_value = map[string]int32{
		"AuthErrorTypeNone":           0,
		"AuthErrorTypeUserWrongCreds": 1,
	}
)

func (x AuthErrorType) Enum() *AuthErrorType {
	p := new(AuthErrorType)
	*p = x
	return p
}

func (x AuthErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[0].Descriptor()
}

func (AuthErrorType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[0]
}

func (x AuthErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorType.Descriptor instead.
func (AuthErrorType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

type RoomMemberStatusType int32

const (
	RoomMemberStatusType_RoomMemberStatusTypeInvited RoomMemberStatusType = 0
	RoomMemberStatusType_RoomMemberStatusTypeJoined  RoomMemberStatusType = 1
	RoomMemberStatusType_RoomMemberStatusTypeLeft    RoomMemberStatusType = 2
	RoomMemberStatusType_RoomMemberStatusTypeKicked  RoomMemberStatusType = 3
	RoomMemberStatusType_RoomMemberStatusTypeBanned  RoomMemberStatusType = 4
)

// Enum value maps for RoomMemberStatusType.
var (
	RoomMemberStatusType_name = map[int32]string{
		0: "RoomMemberStatusTypeInvited",
		1: "RoomMemberStatusTypeJoined",
		2: "RoomMemberStatusTypeLeft",
		3: "RoomMemberStatusTypeKicked",
		4: "RoomMemberStatusTypeBanned",
	}
	RoomMemberStatusType_value = map[string]int32{
		"RoomMemberStatusTypeInvited": 0,
		"RoomMemberStatusTypeJoined":  1,
		"RoomMemberStatusTypeLeft":    2,
		"RoomMemberStatusTypeKicked":  3,
		"RoomMemberStatusTypeBanned":  4,
	}
)

func (x RoomMemberStatusType) Enum() *RoomMemberStatusType {
	p := new(RoomMemberStatusType)
	*p = x
	return p
}

func (x RoomMemberStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMemberStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[1].Descriptor()
}

func (RoomMemberStatusType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[1]
}

func (x RoomMemberStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMemberStatusType.Descriptor instead.
func (RoomMemberStatusType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

type RoomEventType int32

const (
	RoomEventType_roomEventTypeAll     RoomEventType = 0
	RoomEventType_roomEventTypeMessage RoomEventType = 1
	RoomEventType_roomEventTypeSystem  RoomEventType = 2
)

// Enum value maps for RoomEventType.
var (
	RoomEventType_name = map[int32]string{
		0: "roomEventTypeAll",
		1: "roomEventTypeMessage",
		2: "roomEventTypeSystem",
	}
	RoomEventType_value = map[string]int32{
		"roomEventTypeAll":     0,
		"roomEventTypeMessage": 1,
		"roomEventTypeSystem":  2,
	}
)

func (x RoomEventType) Enum() *RoomEventType {
	p := new(RoomEventType)
	*p = x
	return p
}

func (x RoomEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[2].Descriptor()
}

func (RoomEventType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[2]
}

func (x RoomEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomEventType.Descriptor instead.
func (RoomEventType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

type SinceTimeOrderType int32

const (
	SinceTimeOrderType_sinceTimeOrderTypeNewest SinceTimeOrderType = 0
	SinceTimeOrderType_sinceTimeOrderTypeOldest SinceTimeOrderType = 1
)

// Enum value maps for SinceTimeOrderType.
var (
	SinceTimeOrderType_name = map[int32]string{
		0: "sinceTimeOrderTypeNewest",
		1: "sinceTimeOrderTypeOldest",
	}
	SinceTimeOrderType_value = map[string]int32{
		"sinceTimeOrderTypeNewest": 0,
		"sinceTimeOrderTypeOldest": 1,
	}
)

func (x SinceTimeOrderType) Enum() *SinceTimeOrderType {
	p := new(SinceTimeOrderType)
	*p = x
	return p
}

func (x SinceTimeOrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SinceTimeOrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[3].Descriptor()
}

func (SinceTimeOrderType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[3]
}

func (x SinceTimeOrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SinceTimeOrderType.Descriptor instead.
func (SinceTimeOrderType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

type AuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *AuthUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         AuthErrorType          `protobuf:"varint,1,opt,name=error,proto3,enum=ru.alexshniperson.sputnikn.api.contract.v1.AuthErrorType" json:"error,omitempty"`
	AccessToken   *string                `protobuf:"bytes,2,opt,name=accessToken,proto3,oneof" json:"accessToken,omitempty"`
	Detail        *UserDetail            `protobuf:"bytes,3,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserResponse) GetError() AuthErrorType {
	if x != nil {
		return x.Error
	}
	return AuthErrorType_AuthErrorTypeNone
}

func (x *AuthUserResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *AuthUserResponse) GetDetail() *UserDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIds       []string               `protobuf:"bytes,1,rep,name=roomIds,proto3" json:"roomIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoomsRequest) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type RoomMemberDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	IsOnline       bool                   `protobuf:"varint,3,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	MemberStatus   RoomMemberStatusType   `protobuf:"varint,4,opt,name=memberStatus,proto3,enum=ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberStatusType" json:"memberStatus,omitempty"`
	Avatar         *string                `protobuf:"bytes,5,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	LastReadMarker *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastReadMarker,proto3" json:"lastReadMarker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomMemberDetail) Reset() {
	*x = RoomMemberDetail{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMemberDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberDetail) ProtoMessage() {}

func (x *RoomMemberDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberDetail.ProtoReflect.Descriptor instead.
func (*RoomMemberDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *RoomMemberDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMemberDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RoomMemberDetail) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *RoomMemberDetail) GetMemberStatus() RoomMemberStatusType {
	if x != nil {
		return x.MemberStatus
	}
	return RoomMemberStatusType_RoomMemberStatusTypeInvited
}

func (x *RoomMemberDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *RoomMemberDetail) GetLastReadMarker() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadMarker
	}
	return nil
}

// The RoomState, it will be sent to client every time Room is changed (title, avatar, members, member read markers)
type RoomDetail struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RoomId                  string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Title                   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar                  *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Members                 []*RoomMemberDetail    `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	EventMessageUnreadCount int32                  `protobuf:"varint,5,opt,name=eventMessageUnreadCount,proto3" json:"eventMessageUnreadCount,omitempty"`
	EventSystemUnreadCount  int32                  `protobuf:"varint,6,opt,name=eventSystemUnreadCount,proto3" json:"eventSystemUnreadCount,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RoomDetail) Reset() {
	*x = RoomDetail{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDetail) ProtoMessage() {}

func (x *RoomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDetail.ProtoReflect.Descriptor instead.
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *RoomDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *RoomDetail) GetMembers() []*RoomMemberDetail {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomDetail) GetEventMessageUnreadCount() int32 {
	if x != nil {
		return x.EventMessageUnreadCount
	}
	return 0
}

func (x *RoomDetail) GetEventSystemUnreadCount() int32 {
	if x != nil {
		return x.EventSystemUnreadCount
	}
	return 0
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        []*RoomDetail          `protobuf:"bytes,1,rep,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoomsResponse) GetDetail() []*RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SinceTimeFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SinceTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sinceTimestamp,proto3" json:"sinceTimestamp,omitempty"`
	OrderType      SinceTimeOrderType     `protobuf:"varint,2,opt,name=orderType,proto3,enum=ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeOrderType" json:"orderType,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SinceTimeFilter) Reset() {
	*x = SinceTimeFilter{}
	mi := &file_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinceTimeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinceTimeFilter) ProtoMessage() {}

func (x *SinceTimeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinceTimeFilter.ProtoReflect.Descriptor instead.
func (*SinceTimeFilter) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{7}
}

func (x *SinceTimeFilter) GetSinceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceTimestamp
	}
	return nil
}

func (x *SinceTimeFilter) GetOrderType() SinceTimeOrderType {
	if x != nil {
		return x.OrderType
	}
	return SinceTimeOrderType_sinceTimeOrderTypeNewest
}

type SyncRoomFilter struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	// Mean we want to filter room events with offset of time and order direction
	SinceFilter *SinceTimeFilter `protobuf:"bytes,2,opt,name=sinceFilter,proto3,oneof" json:"sinceFilter,omitempty"`
	// Mean we want to filter room events by type
	EventFilter RoomEventType `protobuf:"varint,4,opt,name=eventFilter,proto3,enum=ru.alexshniperson.sputnikn.api.contract.v1.RoomEventType" json:"eventFilter,omitempty"`
	// Mean we want to get limited room events with conjunction of sinceFilter and eventFilter
	EventLimit    int32 `protobuf:"varint,3,opt,name=eventLimit,proto3" json:"eventLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomFilter) Reset() {
	*x = SyncRoomFilter{}
	mi := &file_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomFilter) ProtoMessage() {}

func (x *SyncRoomFilter) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomFilter.ProtoReflect.Descriptor instead.
func (*SyncRoomFilter) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{8}
}

func (x *SyncRoomFilter) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncRoomFilter) GetSinceFilter() *SinceTimeFilter {
	if x != nil {
		return x.SinceFilter
	}
	return nil
}

func (x *SyncRoomFilter) GetEventFilter() RoomEventType {
	if x != nil {
		return x.EventFilter
	}
	return RoomEventType_roomEventTypeAll
}

func (x *SyncRoomFilter) GetEventLimit() int32 {
	if x != nil {
		return x.EventLimit
	}
	return 0
}

type SyncRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomFilter    []*SyncRoomFilter      `protobuf:"bytes,1,rep,name=roomFilter,proto3" json:"roomFilter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomsRequest) Reset() {
	*x = SyncRoomsRequest{}
	mi := &file_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomsRequest) ProtoMessage() {}

func (x *SyncRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomsRequest.ProtoReflect.Descriptor instead.
func (*SyncRoomsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRoomsRequest) GetRoomFilter() []*SyncRoomFilter {
	if x != nil {
		return x.RoomFilter
	}
	return nil
}

type ChatAttachmentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,2,opt,name=attachmentId,proto3" json:"attachmentId,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatAttachmentDetail) Reset() {
	*x = ChatAttachmentDetail{}
	mi := &file_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatAttachmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttachmentDetail) ProtoMessage() {}

func (x *ChatAttachmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttachmentDetail.ProtoReflect.Descriptor instead.
func (*ChatAttachmentDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{10}
}

func (x *ChatAttachmentDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChatAttachmentDetail) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *ChatAttachmentDetail) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type RoomEventReactionDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId          string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createTimestamp,proto3" json:"createTimestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomEventReactionDetail) Reset() {
	*x = RoomEventReactionDetail{}
	mi := &file_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventReactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventReactionDetail) ProtoMessage() {}

func (x *RoomEventReactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventReactionDetail.ProtoReflect.Descriptor instead.
func (*RoomEventReactionDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{11}
}

func (x *RoomEventReactionDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventReactionDetail) GetCreateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTimestamp
	}
	return nil
}

type RoomEventMessageDetail struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	EventId         string                     `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId          string                     `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	SenderId        string                     `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ClientEventId   *int32                     `protobuf:"varint,4,opt,name=clientEventId,proto3,oneof" json:"clientEventId,omitempty"`
	Version         int32                      `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Attachment      []*ChatAttachmentDetail    `protobuf:"bytes,6,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Reaction        []*RoomEventReactionDetail `protobuf:"bytes,7,rep,name=reaction,proto3" json:"reaction,omitempty"`
	Content         string                     `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	CreateTimestamp *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=createTimestamp,proto3" json:"createTimestamp,omitempty"`
	UpdateTimestamp *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=updateTimestamp,proto3" json:"updateTimestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomEventMessageDetail) Reset() {
	*x = RoomEventMessageDetail{}
	mi := &file_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageDetail) ProtoMessage() {}

func (x *RoomEventMessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageDetail.ProtoReflect.Descriptor instead.
func (*RoomEventMessageDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{12}
}

func (x *RoomEventMessageDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetClientEventId() int32 {
	if x != nil && x.ClientEventId != nil {
		return *x.ClientEventId
	}
	return 0
}

func (x *RoomEventMessageDetail) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoomEventMessageDetail) GetAttachment() []*ChatAttachmentDetail {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *RoomEventMessageDetail) GetReaction() []*RoomEventReactionDetail {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *RoomEventMessageDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventMessageDetail) GetCreateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTimestamp
	}
	return nil
}

func (x *RoomEventMessageDetail) GetUpdateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTimestamp
	}
	return nil
}

type RoomEventSystemDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId          string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Version         int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createTimestamp,proto3" json:"createTimestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomEventSystemDetail) Reset() {
	*x = RoomEventSystemDetail{}
	mi := &file_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventSystemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventSystemDetail) ProtoMessage() {}

func (x *RoomEventSystemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventSystemDetail.ProtoReflect.Descriptor instead.
func (*RoomEventSystemDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{13}
}

func (x *RoomEventSystemDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventSystemDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventSystemDetail) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoomEventSystemDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventSystemDetail) GetCreateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTimestamp
	}
	return nil
}

type SyncRoomsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MessageEvents []*RoomEventMessageDetail `protobuf:"bytes,1,rep,name=messageEvents,proto3" json:"messageEvents,omitempty"`
	SystemEvents  []*RoomEventSystemDetail  `protobuf:"bytes,2,rep,name=systemEvents,proto3" json:"systemEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomsResponse) Reset() {
	*x = SyncRoomsResponse{}
	mi := &file_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomsResponse) ProtoMessage() {}

func (x *SyncRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomsResponse.ProtoReflect.Descriptor instead.
func (*SyncRoomsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{14}
}

func (x *SyncRoomsResponse) GetMessageEvents() []*RoomEventMessageDetail {
	if x != nil {
		return x.MessageEvents
	}
	return nil
}

func (x *SyncRoomsResponse) GetSystemEvents() []*RoomEventSystemDetail {
	if x != nil {
		return x.SystemEvents
	}
	return nil
}

type RoomEventMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ClientEventId int32                  `protobuf:"varint,2,opt,name=clientEventId,proto3" json:"clientEventId,omitempty"`
	Attachment    []string               `protobuf:"bytes,3,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageRequest) Reset() {
	*x = RoomEventMessageRequest{}
	mi := &file_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageRequest) ProtoMessage() {}

func (x *RoomEventMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageRequest.ProtoReflect.Descriptor instead.
func (*RoomEventMessageRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{15}
}

func (x *RoomEventMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventMessageRequest) GetClientEventId() int32 {
	if x != nil {
		return x.ClientEventId
	}
	return 0
}

func (x *RoomEventMessageRequest) GetAttachment() []string {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *RoomEventMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventMessageRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RoomEventMessageResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Detail        *RoomEventMessageDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageResponse) Reset() {
	*x = RoomEventMessageResponse{}
	mi := &file_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageResponse) ProtoMessage() {}

func (x *RoomEventMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageResponse.ProtoReflect.Descriptor instead.
func (*RoomEventMessageResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{16}
}

func (x *RoomEventMessageResponse) GetDetail() *RoomEventMessageDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RoomEventReaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ClientEventId int32                  `protobuf:"varint,3,opt,name=clientEventId,proto3" json:"clientEventId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventReaction) Reset() {
	*x = RoomEventReaction{}
	mi := &file_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventReaction) ProtoMessage() {}

func (x *RoomEventReaction) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventReaction.ProtoReflect.Descriptor instead.
func (*RoomEventReaction) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{17}
}

func (x *RoomEventReaction) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventReaction) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RoomEventReaction) GetClientEventId() int32 {
	if x != nil {
		return x.ClientEventId
	}
	return 0
}

func (x *RoomEventReaction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{18}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserDetail          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{19}
}

func (x *ListUsersResponse) GetUsers() []*UserDetail {
	if x != nil {
		return x.Users
	}
	return nil
}

// Will produce RoomStateChangedReply
type RoomReadMarkerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomId              string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ReadMarkerTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=readMarkerTimestamp,proto3" json:"readMarkerTimestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoomReadMarkerRequest) Reset() {
	*x = RoomReadMarkerRequest{}
	mi := &file_contract_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomReadMarkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReadMarkerRequest) ProtoMessage() {}

func (x *RoomReadMarkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReadMarkerRequest.ProtoReflect.Descriptor instead.
func (*RoomReadMarkerRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{20}
}

func (x *RoomReadMarkerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomReadMarkerRequest) GetReadMarkerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadMarkerTimestamp
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	MemberIds     []string               `protobuf:"bytes,3,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_contract_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoomRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *CreateRoomRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RoomDetail            `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_contract_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRoomResponse) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Will produce RoomStateChangedResponse
type InviteRoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoomMember) Reset() {
	*x = InviteRoomMember{}
	mi := &file_contract_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomMember) ProtoMessage() {}

func (x *InviteRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomMember.ProtoReflect.Descriptor instead.
func (*InviteRoomMember) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{23}
}

func (x *InviteRoomMember) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteRoomMember) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// Will produce RoomStateChangedResponse
type RemoveRoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomMember) Reset() {
	*x = RemoveRoomMember{}
	mi := &file_contract_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomMember) ProtoMessage() {}

func (x *RemoveRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomMember.ProtoReflect.Descriptor instead.
func (*RemoveRoomMember) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveRoomMember) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RemoveRoomMember) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type RoomStateChangedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RoomDetail            `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateChangedResponse) Reset() {
	*x = RoomStateChangedResponse{}
	mi := &file_contract_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateChangedResponse) ProtoMessage() {}

func (x *RoomStateChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateChangedResponse.ProtoReflect.Descriptor instead.
func (*RoomStateChangedResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{25}
}

func (x *RoomStateChangedResponse) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RoomEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RoomEventResponse_MessageEvent
	//	*RoomEventResponse_SystemEvent
	//	*RoomEventResponse_RoomStateChanged
	//	*RoomEventResponse_RoomEventMessage
	//	*RoomEventResponse_RoomEventReaction
	Payload       isRoomEventResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventResponse) Reset() {
	*x = RoomEventResponse{}
	mi := &file_contract_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventResponse) ProtoMessage() {}

func (x *RoomEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventResponse.ProtoReflect.Descriptor instead.
func (*RoomEventResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{26}
}

func (x *RoomEventResponse) GetPayload() isRoomEventResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoomEventResponse) GetMessageEvent() *RoomEventMessageDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *RoomEventResponse) GetSystemEvent() *RoomEventSystemDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_SystemEvent); ok {
			return x.SystemEvent
		}
	}
	return nil
}

func (x *RoomEventResponse) GetRoomStateChanged() *RoomStateChangedResponse {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_RoomStateChanged); ok {
			return x.RoomStateChanged
		}
	}
	return nil
}

func (x *RoomEventResponse) GetRoomEventMessage() *RoomEventMessageDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_RoomEventMessage); ok {
			return x.RoomEventMessage
		}
	}
	return nil
}

func (x *RoomEventResponse) GetRoomEventReaction() *RoomEventReactionDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_RoomEventReaction); ok {
			return x.RoomEventReaction
		}
	}
	return nil
}

type isRoomEventResponse_Payload interface {
	isRoomEventResponse_Payload()
}

type RoomEventResponse_MessageEvent struct {
	MessageEvent *RoomEventMessageDetail `protobuf:"bytes,1,opt,name=messageEvent,proto3,oneof"`
}

type RoomEventResponse_SystemEvent struct {
	SystemEvent *RoomEventSystemDetail `protobuf:"bytes,2,opt,name=systemEvent,proto3,oneof"`
}

type RoomEventResponse_RoomStateChanged struct {
	RoomStateChanged *RoomStateChangedResponse `protobuf:"bytes,3,opt,name=roomStateChanged,proto3,oneof"`
}

type RoomEventResponse_RoomEventMessage struct {
	RoomEventMessage *RoomEventMessageDetail `protobuf:"bytes,4,opt,name=roomEventMessage,proto3,oneof"`
}

type RoomEventResponse_RoomEventReaction struct {
	RoomEventReaction *RoomEventReactionDetail `protobuf:"bytes,5,opt,name=roomEventReaction,proto3,oneof"`
}

func (*RoomEventResponse_MessageEvent) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_SystemEvent) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_RoomStateChanged) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_RoomEventMessage) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_RoomEventReaction) isRoomEventResponse_Payload() {}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12*ru.alexshniperson.sputnikn.api.contract.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fAuthUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"h\n" +
	"\n" +
	"UserDetail\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x00R\x06avatar\x88\x01\x01B\t\n" +
	"\a_avatar\"\xfa\x01\n" +
	"\x10AuthUserResponse\x12O\n" +
	"\x05error\x18\x01 \x01(\x0e29.ru.alexshniperson.sputnikn.api.contract.v1.AuthErrorTypeR\x05error\x12%\n" +
	"\vaccessToken\x18\x02 \x01(\tH\x00R\vaccessToken\x88\x01\x01\x12S\n" +
	"\x06detail\x18\x03 \x01(\v26.ru.alexshniperson.sputnikn.api.contract.v1.UserDetailH\x01R\x06detail\x88\x01\x01B\x0e\n" +
	"\f_accessTokenB\t\n" +
	"\a_detail\",\n" +
	"\x10ListRoomsRequest\x12\x18\n" +
	"\aroomIds\x18\x01 \x03(\tR\aroomIds\"\xb4\x02\n" +
	"\x10RoomMemberDetail\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1a\n" +
	"\bisOnline\x18\x03 \x01(\bR\bisOnline\x12d\n" +
	"\fmemberStatus\x18\x04 \x01(\x0e2@.ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberStatusTypeR\fmemberStatus\x12\x1b\n" +
	"\x06avatar\x18\x05 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12B\n" +
	"\x0elastReadMarker\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReadMarkerB\t\n" +
	"\a_avatar\"\xac\x02\n" +
	"\n" +
	"RoomDetail\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12V\n" +
	"\amembers\x18\x04 \x03(\v2<.ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberDetailR\amembers\x128\n" +
	"\x17eventMessageUnreadCount\x18\x05 \x01(\x05R\x17eventMessageUnreadCount\x126\n" +
	"\x16eventSystemUnreadCount\x18\x06 \x01(\x05R\x16eventSystemUnreadCountB\t\n" +
	"\a_avatar\"c\n" +
	"\x11ListRoomsResponse\x12N\n" +
	"\x06detail\x18\x01 \x03(\v26.ru.alexshniperson.sputnikn.api.contract.v1.RoomDetailR\x06detail\"\xb3\x01\n" +
	"\x0fSinceTimeFilter\x12B\n" +
	"\x0esinceTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0esinceTimestamp\x12\\\n" +
	"\torderType\x18\x02 \x01(\x0e2>.ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeOrderTypeR\torderType\"\x99\x02\n" +
	"\x0eSyncRoomFilter\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12b\n" +
	"\vsinceFilter\x18\x02 \x01(\v2;.ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeFilterH\x00R\vsinceFilter\x88\x01\x01\x12[\n" +
	"\veventFilter\x18\x04 \x01(\x0e29.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventTypeR\veventFilter\x12\x1e\n" +
	"\n" +
	"eventLimit\x18\x03 \x01(\x05R\n" +
	"eventLimitB\x0e\n" +
	"\f_sinceFilter\"n\n" +
	"\x10SyncRoomsRequest\x12Z\n" +
	"\n" +
	"roomFilter\x18\x01 \x03(\v2:.ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomFilterR\n" +
	"roomFilter\"p\n" +
	"\x14ChatAttachmentDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\"\n" +
	"\fattachmentId\x18\x02 \x01(\tR\fattachmentId\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\"\xc7\x01\n" +
	"\x17RoomEventReactionDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12D\n" +
	"\x0fcreateTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreateTimestamp\"\xa6\x04\n" +
	"\x16RoomEventMessageDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12)\n" +
	"\rclientEventId\x18\x04 \x01(\x05H\x00R\rclientEventId\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12`\n" +
	"\n" +
	"attachment\x18\x06 \x03(\v2@.ru.alexshniperson.sputnikn.api.contract.v1.ChatAttachmentDetailR\n" +
	"attachment\x12_\n" +
	"\breaction\x18\a \x03(\v2C.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetailR\breaction\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12D\n" +
	"\x0fcreateTimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreateTimestamp\x12D\n" +
	"\x0fupdateTimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0fupdateTimestampB\x10\n" +
	"\x0e_clientEventId\"\xc3\x01\n" +
	"\x15RoomEventSystemDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12D\n" +
	"\x0fcreateTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreateTimestamp\"\xe4\x01\n" +
	"\x11SyncRoomsResponse\x12h\n" +
	"\rmessageEvents\x18\x01 \x03(\v2B.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetailR\rmessageEvents\x12e\n" +
	"\fsystemEvents\x18\x02 \x03(\v2A.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetailR\fsystemEvents\"\xab\x01\n" +
	"\x17RoomEventMessageRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\rclientEventId\x18\x02 \x01(\x05R\rclientEventId\x12\x1e\n" +
	"\n" +
	"attachment\x18\x03 \x03(\tR\n" +
	"attachment\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"v\n" +
	"\x18RoomEventMessageResponse\x12Z\n" +
	"\x06detail\x18\x01 \x01(\v2B.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetailR\x06detail\"\x89\x01\n" +
	"\x11RoomEventReaction\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12$\n" +
	"\rclientEventId\x18\x03 \x01(\x05R\rclientEventId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x12\n" +
	"\x10ListUsersRequest\"a\n" +
	"\x11ListUsersResponse\x12L\n" +
	"\x05users\x18\x01 \x03(\v26.ru.alexshniperson.sputnikn.api.contract.v1.UserDetailR\x05users\"}\n" +
	"\x15RoomReadMarkerRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12L\n" +
	"\x13readMarkerTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13readMarkerTimestamp\"o\n" +
	"\x11CreateRoomRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12\x1c\n" +
	"\tmemberIds\x18\x03 \x03(\tR\tmemberIdsB\t\n" +
	"\a_avatar\"d\n" +
	"\x12CreateRoomResponse\x12N\n" +
	"\x06detail\x18\x01 \x01(\v26.ru.alexshniperson.sputnikn.api.contract.v1.RoomDetailR\x06detail\"H\n" +
	"\x10InviteRoomMember\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\tR\tmemberIds\"H\n" +
	"\x10RemoveRoomMember\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\tR\tmemberIds\"j\n" +
	"\x18RoomStateChangedResponse\x12N\n" +
	"\x06detail\x18\x01 \x01(\v26.ru.alexshniperson.sputnikn.api.contract.v1.RoomDetailR\x06detail\"\xca\x04\n" +
	"\x11RoomEventResponse\x12h\n" +
	"\fmessageEvent\x18\x01 \x01(\v2B.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetailH\x00R\fmessageEvent\x12e\n" +
	"\vsystemEvent\x18\x02 \x01(\v2A.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetailH\x00R\vsystemEvent\x12r\n" +
	"\x10roomStateChanged\x18\x03 \x01(\v2D.ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponseH\x00R\x10roomStateChanged\x12p\n" +
	"\x10roomEventMessage\x18\x04 \x01(\v2B.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetailH\x00R\x10roomEventMessage\x12s\n" +
	"\x11roomEventReaction\x18\x05 \x01(\v2C.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetailH\x00R\x11roomEventReactionB\t\n" +
	"\apayload*G\n" +
	"\rAuthErrorType\x12\x15\n" +
	"\x11AuthErrorTypeNone\x10\x00\x12\x1f\n" +
	"\x1bAuthErrorTypeUserWrongCreds\x10\x01*\xb5\x01\n" +
	"\x14RoomMemberStatusType\x12\x1f\n" +
	"\x1bRoomMemberStatusTypeInvited\x10\x00\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeJoined\x10\x01\x12\x1c\n" +
	"\x18RoomMemberStatusTypeLeft\x10\x02\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeKicked\x10\x03\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeBanned\x10\x04*X\n" +
	"\rRoomEventType\x12\x14\n" +
	"\x10roomEventTypeAll\x10\x00\x12\x18\n" +
	"\x14roomEventTypeMessage\x10\x01\x12\x17\n" +
	"\x13roomEventTypeSystem\x10\x02*P\n" +
	"\x12SinceTimeOrderType\x12\x1c\n" +
	"\x18sinceTimeOrderTypeNewest\x10\x00\x12\x1c\n" +
	"\x18sinceTimeOrderTypeOldest\x10\x012\xd5\n" +
	"\n" +
	"\vChatService\x12\x85\x01\n" +
	"\bAuthUser\x12;.ru.alexshniperson.sputnikn.api.contract.v1.AuthUserRequest\x1a<.ru.alexshniperson.sputnikn.api.contract.v1.AuthUserResponse\x12\x88\x01\n" +
	"\tListRooms\x12<.ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsRequest\x1a=.ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsResponse\x12\x88\x01\n" +
	"\tSyncRooms\x12<.ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsRequest\x1a=.ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsResponse\x12\x88\x01\n" +
	"\tListUsers\x12<.ru.alexshniperson.sputnikn.api.contract.v1.ListUsersRequest\x1a=.ru.alexshniperson.sputnikn.api.contract.v1.ListUsersResponse\x12\x9c\x01\n" +
	"\x11SetRoomReadMarker\x12A.ru.alexshniperson.sputnikn.api.contract.v1.RoomReadMarkerRequest\x1aD.ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse\x12\x8b\x01\n" +
	"\n" +
	"CreateRoom\x12=.ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomRequest\x1a>.ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomResponse\x12p\n" +
	"\x10InviteRoomMember\x12\x16.google.protobuf.Empty\x1aD.ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse\x12p\n" +
	"\x10RemoveRoomMember\x12\x16.google.protobuf.Empty\x1aD.ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse\x12\x9b\x01\n" +
	"\x0eAddRoomMessage\x12C.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageRequest\x1aD.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageResponse\x12n\n" +
	"\x13SubscribeRoomEvents\x12\x16.google.protobuf.Empty\x1a=.ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse0\x01B\rZ\vcontract/v1b\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_contract_proto_goTypes = []any{
	(AuthErrorType)(0),               // 0: ru.alexshniperson.sputnikn.api.contract.v1.AuthErrorType
	(RoomMemberStatusType)(0),        // 1: ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberStatusType
	(RoomEventType)(0),               // 2: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventType
	(SinceTimeOrderType)(0),          // 3: ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeOrderType
	(*AuthUserRequest)(nil),          // 4: ru.alexshniperson.sputnikn.api.contract.v1.AuthUserRequest
	(*UserDetail)(nil),               // 5: ru.alexshniperson.sputnikn.api.contract.v1.UserDetail
	(*AuthUserResponse)(nil),         // 6: ru.alexshniperson.sputnikn.api.contract.v1.AuthUserResponse
	(*ListRoomsRequest)(nil),         // 7: ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsRequest
	(*RoomMemberDetail)(nil),         // 8: ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberDetail
	(*RoomDetail)(nil),               // 9: ru.alexshniperson.sputnikn.api.contract.v1.RoomDetail
	(*ListRoomsResponse)(nil),        // 10: ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsResponse
	(*SinceTimeFilter)(nil),          // 11: ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeFilter
	(*SyncRoomFilter)(nil),           // 12: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomFilter
	(*SyncRoomsRequest)(nil),         // 13: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsRequest
	(*ChatAttachmentDetail)(nil),     // 14: ru.alexshniperson.sputnikn.api.contract.v1.ChatAttachmentDetail
	(*RoomEventReactionDetail)(nil),  // 15: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetail
	(*RoomEventMessageDetail)(nil),   // 16: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail
	(*RoomEventSystemDetail)(nil),    // 17: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetail
	(*SyncRoomsResponse)(nil),        // 18: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsResponse
	(*RoomEventMessageRequest)(nil),  // 19: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageRequest
	(*RoomEventMessageResponse)(nil), // 20: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageResponse
	(*RoomEventReaction)(nil),        // 21: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReaction
	(*ListUsersRequest)(nil),         // 22: ru.alexshniperson.sputnikn.api.contract.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 23: ru.alexshniperson.sputnikn.api.contract.v1.ListUsersResponse
	(*RoomReadMarkerRequest)(nil),    // 24: ru.alexshniperson.sputnikn.api.contract.v1.RoomReadMarkerRequest
	(*CreateRoomRequest)(nil),        // 25: ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),       // 26: ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomResponse
	(*InviteRoomMember)(nil),         // 27: ru.alexshniperson.sputnikn.api.contract.v1.InviteRoomMember
	(*RemoveRoomMember)(nil),         // 28: ru.alexshniperson.sputnikn.api.contract.v1.RemoveRoomMember
	(*RoomStateChangedResponse)(nil), // 29: ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse
	(*RoomEventResponse)(nil),        // 30: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse
	(*timestamppb.Timestamp)(nil),    // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 32: google.protobuf.Empty
}
var file_contract_proto_depIdxs = []int32{
	0,  // 0: ru.alexshniperson.sputnikn.api.contract.v1.AuthUserResponse.error:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.AuthErrorType
	5,  // 1: ru.alexshniperson.sputnikn.api.contract.v1.AuthUserResponse.detail:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.UserDetail
	1,  // 2: ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberDetail.memberStatus:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberStatusType
	31, // 3: ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberDetail.lastReadMarker:type_name -> google.protobuf.Timestamp
	8,  // 4: ru.alexshniperson.sputnikn.api.contract.v1.RoomDetail.members:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomMemberDetail
	9,  // 5: ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsResponse.detail:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomDetail
	31, // 6: ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeFilter.sinceTimestamp:type_name -> google.protobuf.Timestamp
	3,  // 7: ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeFilter.orderType:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeOrderType
	11, // 8: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomFilter.sinceFilter:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.SinceTimeFilter
	2,  // 9: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomFilter.eventFilter:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventType
	12, // 10: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsRequest.roomFilter:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomFilter
	31, // 11: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetail.createTimestamp:type_name -> google.protobuf.Timestamp
	14, // 12: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail.attachment:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.ChatAttachmentDetail
	15, // 13: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail.reaction:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetail
	31, // 14: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail.createTimestamp:type_name -> google.protobuf.Timestamp
	31, // 15: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail.updateTimestamp:type_name -> google.protobuf.Timestamp
	31, // 16: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetail.createTimestamp:type_name -> google.protobuf.Timestamp
	16, // 17: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsResponse.messageEvents:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail
	17, // 18: ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsResponse.systemEvents:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetail
	16, // 19: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageResponse.detail:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail
	5,  // 20: ru.alexshniperson.sputnikn.api.contract.v1.ListUsersResponse.users:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.UserDetail
	31, // 21: ru.alexshniperson.sputnikn.api.contract.v1.RoomReadMarkerRequest.readMarkerTimestamp:type_name -> google.protobuf.Timestamp
	9,  // 22: ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomResponse.detail:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomDetail
	9,  // 23: ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse.detail:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomDetail
	16, // 24: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse.messageEvent:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail
	17, // 25: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse.systemEvent:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventSystemDetail
	29, // 26: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse.roomStateChanged:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse
	16, // 27: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse.roomEventMessage:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageDetail
	15, // 28: ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse.roomEventReaction:type_name -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventReactionDetail
	4,  // 29: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.AuthUser:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.AuthUserRequest
	7,  // 30: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.ListRooms:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsRequest
	13, // 31: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SyncRooms:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsRequest
	22, // 32: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.ListUsers:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.ListUsersRequest
	24, // 33: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SetRoomReadMarker:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomReadMarkerRequest
	25, // 34: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.CreateRoom:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomRequest
	32, // 35: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.InviteRoomMember:input_type -> google.protobuf.Empty
	32, // 36: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.RemoveRoomMember:input_type -> google.protobuf.Empty
	19, // 37: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.AddRoomMessage:input_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageRequest
	32, // 38: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SubscribeRoomEvents:input_type -> google.protobuf.Empty
	6,  // 39: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.AuthUser:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.AuthUserResponse
	10, // 40: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.ListRooms:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.ListRoomsResponse
	18, // 41: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SyncRooms:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.SyncRoomsResponse
	23, // 42: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.ListUsers:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.ListUsersResponse
	29, // 43: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SetRoomReadMarker:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse
	26, // 44: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.CreateRoom:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.CreateRoomResponse
	29, // 45: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.InviteRoomMember:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse
	29, // 46: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.RemoveRoomMember:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomStateChangedResponse
	20, // 47: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.AddRoomMessage:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventMessageResponse
	30, // 48: ru.alexshniperson.sputnikn.api.contract.v1.ChatService.SubscribeRoomEvents:output_type -> ru.alexshniperson.sputnikn.api.contract.v1.RoomEventResponse
	39, // [39:49] is the sub-list for method output_type
	29, // [29:39] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	file_contract_proto_msgTypes[1].OneofWrappers = []any{}
	file_contract_proto_msgTypes[2].OneofWrappers = []any{}
	file_contract_proto_msgTypes[4].OneofWrappers = []any{}
	file_contract_proto_msgTypes[5].OneofWrappers = []any{}
	file_contract_proto_msgTypes[8].OneofWrappers = []any{}
	file_contract_proto_msgTypes[12].OneofWrappers = []any{}
	file_contract_proto_msgTypes[21].OneofWrappers = []any{}
	file_contract_proto_msgTypes[26].OneofWrappers = []any{
		(*RoomEventResponse_MessageEvent)(nil),
		(*RoomEventResponse_SystemEvent)(nil),
		(*RoomEventResponse_RoomStateChanged)(nil),
		(*RoomEventResponse_RoomEventMessage)(nil),
		(*RoomEventResponse_RoomEventReaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		EnumInfos:         file_contract_proto_enumTypes,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
