// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: contract.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_AuthUser_FullMethodName               = "/ru.sputnikn.api.contract.v1.ChatService/AuthUser"
	ChatService_ListRooms_FullMethodName              = "/ru.sputnikn.api.contract.v1.ChatService/ListRooms"
	ChatService_SyncRooms_FullMethodName              = "/ru.sputnikn.api.contract.v1.ChatService/SyncRooms"
	ChatService_ListUsers_FullMethodName              = "/ru.sputnikn.api.contract.v1.ChatService/ListUsers"
	ChatService_SetRoomReadMarker_FullMethodName      = "/ru.sputnikn.api.contract.v1.ChatService/SetRoomReadMarker"
	ChatService_CreateRoom_FullMethodName             = "/ru.sputnikn.api.contract.v1.ChatService/CreateRoom"
	ChatService_InviteRoomMember_FullMethodName       = "/ru.sputnikn.api.contract.v1.ChatService/InviteRoomMember"
	ChatService_RemoveRoomMember_FullMethodName       = "/ru.sputnikn.api.contract.v1.ChatService/RemoveRoomMember"
	ChatService_AddRoomMessage_FullMethodName         = "/ru.sputnikn.api.contract.v1.ChatService/AddRoomMessage"
	ChatService_AddRoomMessageReaction_FullMethodName = "/ru.sputnikn.api.contract.v1.ChatService/AddRoomMessageReaction"
	ChatService_SubscribeRoomEvents_FullMethodName    = "/ru.sputnikn.api.contract.v1.ChatService/SubscribeRoomEvents"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error)
	ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
	SyncRooms(ctx context.Context, in *SyncRoomsRequest, opts ...grpc.CallOption) (*SyncRoomsResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	SetRoomReadMarker(ctx context.Context, in *RoomReadMarkerRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error)
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	InviteRoomMember(ctx context.Context, in *InviteRoomMemberRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error)
	RemoveRoomMember(ctx context.Context, in *RemoveRoomMemberRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error)
	AddRoomMessage(ctx context.Context, in *RoomEventMessageRequest, opts ...grpc.CallOption) (*RoomEventMessageResponse, error)
	AddRoomMessageReaction(ctx context.Context, in *RoomEventMessageReactionRequest, opts ...grpc.CallOption) (*RoomEventMessageReactionResponse, error)
	SubscribeRoomEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoomEventResponse], error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUserResponse)
	err := c.cc.Invoke(ctx, ChatService_AuthUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SyncRooms(ctx context.Context, in *SyncRoomsRequest, opts ...grpc.CallOption) (*SyncRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncRoomsResponse)
	err := c.cc.Invoke(ctx, ChatService_SyncRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, ChatService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetRoomReadMarker(ctx context.Context, in *RoomReadMarkerRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomStateChangedResponse)
	err := c.cc.Invoke(ctx, ChatService_SetRoomReadMarker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, ChatService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) InviteRoomMember(ctx context.Context, in *InviteRoomMemberRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomStateChangedResponse)
	err := c.cc.Invoke(ctx, ChatService_InviteRoomMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RemoveRoomMember(ctx context.Context, in *RemoveRoomMemberRequest, opts ...grpc.CallOption) (*RoomStateChangedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomStateChangedResponse)
	err := c.cc.Invoke(ctx, ChatService_RemoveRoomMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddRoomMessage(ctx context.Context, in *RoomEventMessageRequest, opts ...grpc.CallOption) (*RoomEventMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEventMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_AddRoomMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddRoomMessageReaction(ctx context.Context, in *RoomEventMessageReactionRequest, opts ...grpc.CallOption) (*RoomEventMessageReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEventMessageReactionResponse)
	err := c.cc.Invoke(ctx, ChatService_AddRoomMessageReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SubscribeRoomEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoomEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_SubscribeRoomEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, RoomEventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SubscribeRoomEventsClient = grpc.ServerStreamingClient[RoomEventResponse]

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error)
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
	SyncRooms(context.Context, *SyncRoomsRequest) (*SyncRoomsResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	SetRoomReadMarker(context.Context, *RoomReadMarkerRequest) (*RoomStateChangedResponse, error)
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	InviteRoomMember(context.Context, *InviteRoomMemberRequest) (*RoomStateChangedResponse, error)
	RemoveRoomMember(context.Context, *RemoveRoomMemberRequest) (*RoomStateChangedResponse, error)
	AddRoomMessage(context.Context, *RoomEventMessageRequest) (*RoomEventMessageResponse, error)
	AddRoomMessageReaction(context.Context, *RoomEventMessageReactionRequest) (*RoomEventMessageReactionResponse, error)
	SubscribeRoomEvents(*emptypb.Empty, grpc.ServerStreamingServer[RoomEventResponse]) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedChatServiceServer) ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedChatServiceServer) SyncRooms(context.Context, *SyncRoomsRequest) (*SyncRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncRooms not implemented")
}
func (UnimplementedChatServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedChatServiceServer) SetRoomReadMarker(context.Context, *RoomReadMarkerRequest) (*RoomStateChangedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoomReadMarker not implemented")
}
func (UnimplementedChatServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedChatServiceServer) InviteRoomMember(context.Context, *InviteRoomMemberRequest) (*RoomStateChangedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteRoomMember not implemented")
}
func (UnimplementedChatServiceServer) RemoveRoomMember(context.Context, *RemoveRoomMemberRequest) (*RoomStateChangedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRoomMember not implemented")
}
func (UnimplementedChatServiceServer) AddRoomMessage(context.Context, *RoomEventMessageRequest) (*RoomEventMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoomMessage not implemented")
}
func (UnimplementedChatServiceServer) AddRoomMessageReaction(context.Context, *RoomEventMessageReactionRequest) (*RoomEventMessageReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoomMessageReaction not implemented")
}
func (UnimplementedChatServiceServer) SubscribeRoomEvents(*emptypb.Empty, grpc.ServerStreamingServer[RoomEventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRoomEvents not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AuthUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListRooms(ctx, req.(*ListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SyncRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SyncRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SyncRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SyncRooms(ctx, req.(*SyncRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetRoomReadMarker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReadMarkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetRoomReadMarker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetRoomReadMarker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetRoomReadMarker(ctx, req.(*RoomReadMarkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_InviteRoomMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteRoomMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).InviteRoomMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_InviteRoomMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).InviteRoomMember(ctx, req.(*InviteRoomMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RemoveRoomMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoomMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RemoveRoomMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_RemoveRoomMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RemoveRoomMember(ctx, req.(*RemoveRoomMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddRoomMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomEventMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddRoomMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AddRoomMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddRoomMessage(ctx, req.(*RoomEventMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddRoomMessageReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomEventMessageReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddRoomMessageReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AddRoomMessageReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddRoomMessageReaction(ctx, req.(*RoomEventMessageReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SubscribeRoomEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).SubscribeRoomEvents(m, &grpc.GenericServerStream[emptypb.Empty, RoomEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SubscribeRoomEventsServer = grpc.ServerStreamingServer[RoomEventResponse]

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ru.sputnikn.api.contract.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthUser",
			Handler:    _ChatService_AuthUser_Handler,
		},
		{
			MethodName: "ListRooms",
			Handler:    _ChatService_ListRooms_Handler,
		},
		{
			MethodName: "SyncRooms",
			Handler:    _ChatService_SyncRooms_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _ChatService_ListUsers_Handler,
		},
		{
			MethodName: "SetRoomReadMarker",
			Handler:    _ChatService_SetRoomReadMarker_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _ChatService_CreateRoom_Handler,
		},
		{
			MethodName: "InviteRoomMember",
			Handler:    _ChatService_InviteRoomMember_Handler,
		},
		{
			MethodName: "RemoveRoomMember",
			Handler:    _ChatService_RemoveRoomMember_Handler,
		},
		{
			MethodName: "AddRoomMessage",
			Handler:    _ChatService_AddRoomMessage_Handler,
		},
		{
			MethodName: "AddRoomMessageReaction",
			Handler:    _ChatService_AddRoomMessageReaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRoomEvents",
			Handler:       _ChatService_SubscribeRoomEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contract.proto",
}
