// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: contract.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthErrorType int32

const (
	AuthErrorType_AuthErrorTypeNone           AuthErrorType = 0
	AuthErrorType_AuthErrorTypeUserWrongCreds AuthErrorType = 1
)

// Enum value maps for AuthErrorType.
var (
	AuthErrorType_name = map[int32]string{
		0: "AuthErrorTypeNone",
		1: "AuthErrorTypeUserWrongCreds",
	}
	AuthErrorType_value = map[string]int32{
		"AuthErrorTypeNone":           0,
		"AuthErrorTypeUserWrongCreds": 1,
	}
)

func (x AuthErrorType) Enum() *AuthErrorType {
	p := new(AuthErrorType)
	*p = x
	return p
}

func (x AuthErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[0].Descriptor()
}

func (AuthErrorType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[0]
}

func (x AuthErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorType.Descriptor instead.
func (AuthErrorType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

type RoomMemberStatusType int32

const (
	RoomMemberStatusType_RoomMemberStatusTypeInvited RoomMemberStatusType = 0
	RoomMemberStatusType_RoomMemberStatusTypeJoined  RoomMemberStatusType = 1
	RoomMemberStatusType_RoomMemberStatusTypeLeft    RoomMemberStatusType = 2
	RoomMemberStatusType_RoomMemberStatusTypeKicked  RoomMemberStatusType = 3
	RoomMemberStatusType_RoomMemberStatusTypeBanned  RoomMemberStatusType = 4
)

// Enum value maps for RoomMemberStatusType.
var (
	RoomMemberStatusType_name = map[int32]string{
		0: "RoomMemberStatusTypeInvited",
		1: "RoomMemberStatusTypeJoined",
		2: "RoomMemberStatusTypeLeft",
		3: "RoomMemberStatusTypeKicked",
		4: "RoomMemberStatusTypeBanned",
	}
	RoomMemberStatusType_value = map[string]int32{
		"RoomMemberStatusTypeInvited": 0,
		"RoomMemberStatusTypeJoined":  1,
		"RoomMemberStatusTypeLeft":    2,
		"RoomMemberStatusTypeKicked":  3,
		"RoomMemberStatusTypeBanned":  4,
	}
)

func (x RoomMemberStatusType) Enum() *RoomMemberStatusType {
	p := new(RoomMemberStatusType)
	*p = x
	return p
}

func (x RoomMemberStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomMemberStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[1].Descriptor()
}

func (RoomMemberStatusType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[1]
}

func (x RoomMemberStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomMemberStatusType.Descriptor instead.
func (RoomMemberStatusType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

type RoomEventType int32

const (
	RoomEventType_roomEventTypeAll     RoomEventType = 0
	RoomEventType_roomEventTypeMessage RoomEventType = 1
	RoomEventType_roomEventTypeSystem  RoomEventType = 2
)

// Enum value maps for RoomEventType.
var (
	RoomEventType_name = map[int32]string{
		0: "roomEventTypeAll",
		1: "roomEventTypeMessage",
		2: "roomEventTypeSystem",
	}
	RoomEventType_value = map[string]int32{
		"roomEventTypeAll":     0,
		"roomEventTypeMessage": 1,
		"roomEventTypeSystem":  2,
	}
)

func (x RoomEventType) Enum() *RoomEventType {
	p := new(RoomEventType)
	*p = x
	return p
}

func (x RoomEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[2].Descriptor()
}

func (RoomEventType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[2]
}

func (x RoomEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomEventType.Descriptor instead.
func (RoomEventType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

type SinceTimeOrderType int32

const (
	SinceTimeOrderType_sinceTimeOrderTypeNewest SinceTimeOrderType = 0
	SinceTimeOrderType_sinceTimeOrderTypeOldest SinceTimeOrderType = 1
)

// Enum value maps for SinceTimeOrderType.
var (
	SinceTimeOrderType_name = map[int32]string{
		0: "sinceTimeOrderTypeNewest",
		1: "sinceTimeOrderTypeOldest",
	}
	SinceTimeOrderType_value = map[string]int32{
		"sinceTimeOrderTypeNewest": 0,
		"sinceTimeOrderTypeOldest": 1,
	}
)

func (x SinceTimeOrderType) Enum() *SinceTimeOrderType {
	p := new(SinceTimeOrderType)
	*p = x
	return p
}

func (x SinceTimeOrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SinceTimeOrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_proto_enumTypes[3].Descriptor()
}

func (SinceTimeOrderType) Type() protoreflect.EnumType {
	return &file_contract_proto_enumTypes[3]
}

func (x SinceTimeOrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SinceTimeOrderType.Descriptor instead.
func (SinceTimeOrderType) EnumDescriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

type AuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *AuthUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         AuthErrorType          `protobuf:"varint,1,opt,name=error,proto3,enum=ru.sputnikn.api.contract.v1.AuthErrorType" json:"error,omitempty"`
	AccessToken   *string                `protobuf:"bytes,2,opt,name=accessToken,proto3,oneof" json:"accessToken,omitempty"`
	Detail        *UserDetail            `protobuf:"bytes,3,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserResponse) GetError() AuthErrorType {
	if x != nil {
		return x.Error
	}
	return AuthErrorType_AuthErrorTypeNone
}

func (x *AuthUserResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *AuthUserResponse) GetDetail() *UserDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomIds       []string               `protobuf:"bytes,1,rep,name=roomIds,proto3" json:"roomIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoomsRequest) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type RoomMemberDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	IsOnline       bool                   `protobuf:"varint,3,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	MemberStatus   RoomMemberStatusType   `protobuf:"varint,4,opt,name=memberStatus,proto3,enum=ru.sputnikn.api.contract.v1.RoomMemberStatusType" json:"memberStatus,omitempty"`
	Avatar         *string                `protobuf:"bytes,5,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	LastReadMarker *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastReadMarker,proto3" json:"lastReadMarker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomMemberDetail) Reset() {
	*x = RoomMemberDetail{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMemberDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberDetail) ProtoMessage() {}

func (x *RoomMemberDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberDetail.ProtoReflect.Descriptor instead.
func (*RoomMemberDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *RoomMemberDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMemberDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RoomMemberDetail) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *RoomMemberDetail) GetMemberStatus() RoomMemberStatusType {
	if x != nil {
		return x.MemberStatus
	}
	return RoomMemberStatusType_RoomMemberStatusTypeInvited
}

func (x *RoomMemberDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *RoomMemberDetail) GetLastReadMarker() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadMarker
	}
	return nil
}

// The RoomState, it will be sent to client every time Room is changed (title, avatar, members, member read markers)
type RoomDetail struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RoomId                  string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Title                   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Avatar                  *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Members                 []*RoomMemberDetail    `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	EventMessageUnreadCount int32                  `protobuf:"varint,5,opt,name=eventMessageUnreadCount,proto3" json:"eventMessageUnreadCount,omitempty"`
	EventSystemUnreadCount  int32                  `protobuf:"varint,6,opt,name=eventSystemUnreadCount,proto3" json:"eventSystemUnreadCount,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RoomDetail) Reset() {
	*x = RoomDetail{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDetail) ProtoMessage() {}

func (x *RoomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDetail.ProtoReflect.Descriptor instead.
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *RoomDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomDetail) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *RoomDetail) GetMembers() []*RoomMemberDetail {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomDetail) GetEventMessageUnreadCount() int32 {
	if x != nil {
		return x.EventMessageUnreadCount
	}
	return 0
}

func (x *RoomDetail) GetEventSystemUnreadCount() int32 {
	if x != nil {
		return x.EventSystemUnreadCount
	}
	return 0
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        []*RoomDetail          `protobuf:"bytes,1,rep,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoomsResponse) GetDetail() []*RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SinceTimeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	OrderType     SinceTimeOrderType     `protobuf:"varint,2,opt,name=orderType,proto3,enum=ru.sputnikn.api.contract.v1.SinceTimeOrderType" json:"orderType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinceTimeFilter) Reset() {
	*x = SinceTimeFilter{}
	mi := &file_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinceTimeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinceTimeFilter) ProtoMessage() {}

func (x *SinceTimeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinceTimeFilter.ProtoReflect.Descriptor instead.
func (*SinceTimeFilter) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{7}
}

func (x *SinceTimeFilter) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *SinceTimeFilter) GetOrderType() SinceTimeOrderType {
	if x != nil {
		return x.OrderType
	}
	return SinceTimeOrderType_sinceTimeOrderTypeNewest
}

type SyncRoomFilter struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	// Mean we want to filter room events with offset of time and order direction
	SinceFilter *SinceTimeFilter `protobuf:"bytes,2,opt,name=sinceFilter,proto3,oneof" json:"sinceFilter,omitempty"`
	// Mean we want to filter room events by type
	EventFilter RoomEventType `protobuf:"varint,4,opt,name=eventFilter,proto3,enum=ru.sputnikn.api.contract.v1.RoomEventType" json:"eventFilter,omitempty"`
	// Mean we want to get limited room events with conjunction of sinceFilter and eventFilter
	EventLimit    int32 `protobuf:"varint,3,opt,name=eventLimit,proto3" json:"eventLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomFilter) Reset() {
	*x = SyncRoomFilter{}
	mi := &file_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomFilter) ProtoMessage() {}

func (x *SyncRoomFilter) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomFilter.ProtoReflect.Descriptor instead.
func (*SyncRoomFilter) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{8}
}

func (x *SyncRoomFilter) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncRoomFilter) GetSinceFilter() *SinceTimeFilter {
	if x != nil {
		return x.SinceFilter
	}
	return nil
}

func (x *SyncRoomFilter) GetEventFilter() RoomEventType {
	if x != nil {
		return x.EventFilter
	}
	return RoomEventType_roomEventTypeAll
}

func (x *SyncRoomFilter) GetEventLimit() int32 {
	if x != nil {
		return x.EventLimit
	}
	return 0
}

type SyncRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomFilter    []*SyncRoomFilter      `protobuf:"bytes,1,rep,name=roomFilter,proto3" json:"roomFilter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomsRequest) Reset() {
	*x = SyncRoomsRequest{}
	mi := &file_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomsRequest) ProtoMessage() {}

func (x *SyncRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomsRequest.ProtoReflect.Descriptor instead.
func (*SyncRoomsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRoomsRequest) GetRoomFilter() []*SyncRoomFilter {
	if x != nil {
		return x.RoomFilter
	}
	return nil
}

type ChatAttachmentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	AttachmentId  string                 `protobuf:"bytes,2,opt,name=attachmentId,proto3" json:"attachmentId,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatAttachmentDetail) Reset() {
	*x = ChatAttachmentDetail{}
	mi := &file_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatAttachmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAttachmentDetail) ProtoMessage() {}

func (x *ChatAttachmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAttachmentDetail.ProtoReflect.Descriptor instead.
func (*ChatAttachmentDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{10}
}

func (x *ChatAttachmentDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChatAttachmentDetail) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *ChatAttachmentDetail) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type RoomEventReactionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventReactionDetail) Reset() {
	*x = RoomEventReactionDetail{}
	mi := &file_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventReactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventReactionDetail) ProtoMessage() {}

func (x *RoomEventReactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventReactionDetail.ProtoReflect.Descriptor instead.
func (*RoomEventReactionDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{11}
}

func (x *RoomEventReactionDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RoomEventReactionDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventReactionDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RoomEventMessageDetail struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	EventId       string                     `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId        string                     `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	SenderId      string                     `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Version       int32                      `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Attachment    []*ChatAttachmentDetail    `protobuf:"bytes,5,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Reaction      []*RoomEventReactionDetail `protobuf:"bytes,6,rep,name=reaction,proto3" json:"reaction,omitempty"`
	Content       string                     `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageDetail) Reset() {
	*x = RoomEventMessageDetail{}
	mi := &file_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageDetail) ProtoMessage() {}

func (x *RoomEventMessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageDetail.ProtoReflect.Descriptor instead.
func (*RoomEventMessageDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{12}
}

func (x *RoomEventMessageDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RoomEventMessageDetail) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoomEventMessageDetail) GetAttachment() []*ChatAttachmentDetail {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *RoomEventMessageDetail) GetReaction() []*RoomEventReactionDetail {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *RoomEventMessageDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventMessageDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomEventMessageDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoomEventSystemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventSystemDetail) Reset() {
	*x = RoomEventSystemDetail{}
	mi := &file_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventSystemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventSystemDetail) ProtoMessage() {}

func (x *RoomEventSystemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventSystemDetail.ProtoReflect.Descriptor instead.
func (*RoomEventSystemDetail) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{13}
}

func (x *RoomEventSystemDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEventSystemDetail) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventSystemDetail) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoomEventSystemDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventSystemDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SyncRoomsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MessageEvents []*RoomEventMessageDetail `protobuf:"bytes,1,rep,name=messageEvents,proto3" json:"messageEvents,omitempty"`
	SystemEvents  []*RoomEventSystemDetail  `protobuf:"bytes,2,rep,name=systemEvents,proto3" json:"systemEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomsResponse) Reset() {
	*x = SyncRoomsResponse{}
	mi := &file_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomsResponse) ProtoMessage() {}

func (x *SyncRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomsResponse.ProtoReflect.Descriptor instead.
func (*SyncRoomsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{14}
}

func (x *SyncRoomsResponse) GetMessageEvents() []*RoomEventMessageDetail {
	if x != nil {
		return x.MessageEvents
	}
	return nil
}

func (x *SyncRoomsResponse) GetSystemEvents() []*RoomEventSystemDetail {
	if x != nil {
		return x.SystemEvents
	}
	return nil
}

type RoomEventMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Attachment    []string               `protobuf:"bytes,2,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageRequest) Reset() {
	*x = RoomEventMessageRequest{}
	mi := &file_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageRequest) ProtoMessage() {}

func (x *RoomEventMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageRequest.ProtoReflect.Descriptor instead.
func (*RoomEventMessageRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{15}
}

func (x *RoomEventMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventMessageRequest) GetAttachment() []string {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *RoomEventMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventMessageRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RoomEventMessageResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Detail        *RoomEventMessageDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageResponse) Reset() {
	*x = RoomEventMessageResponse{}
	mi := &file_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageResponse) ProtoMessage() {}

func (x *RoomEventMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageResponse.ProtoReflect.Descriptor instead.
func (*RoomEventMessageResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{16}
}

func (x *RoomEventMessageResponse) GetDetail() *RoomEventMessageDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RoomEventMessageReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ClientEventId int32                  `protobuf:"varint,3,opt,name=clientEventId,proto3" json:"clientEventId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageReactionRequest) Reset() {
	*x = RoomEventMessageReactionRequest{}
	mi := &file_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageReactionRequest) ProtoMessage() {}

func (x *RoomEventMessageReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageReactionRequest.ProtoReflect.Descriptor instead.
func (*RoomEventMessageReactionRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{17}
}

func (x *RoomEventMessageReactionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEventMessageReactionRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RoomEventMessageReactionRequest) GetClientEventId() int32 {
	if x != nil {
		return x.ClientEventId
	}
	return 0
}

func (x *RoomEventMessageReactionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomEventMessageReactionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RoomEventMessageReactionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Detail        *RoomEventReactionDetail `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventMessageReactionResponse) Reset() {
	*x = RoomEventMessageReactionResponse{}
	mi := &file_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventMessageReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventMessageReactionResponse) ProtoMessage() {}

func (x *RoomEventMessageReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventMessageReactionResponse.ProtoReflect.Descriptor instead.
func (*RoomEventMessageReactionResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{18}
}

func (x *RoomEventMessageReactionResponse) GetDetail() *RoomEventReactionDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{19}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserDetail          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_contract_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{20}
}

func (x *ListUsersResponse) GetUsers() []*UserDetail {
	if x != nil {
		return x.Users
	}
	return nil
}

// Will produce RoomStateChangedReply
type RoomReadMarkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ReadMarker    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=readMarker,proto3" json:"readMarker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomReadMarkerRequest) Reset() {
	*x = RoomReadMarkerRequest{}
	mi := &file_contract_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomReadMarkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomReadMarkerRequest) ProtoMessage() {}

func (x *RoomReadMarkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomReadMarkerRequest.ProtoReflect.Descriptor instead.
func (*RoomReadMarkerRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{21}
}

func (x *RoomReadMarkerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomReadMarkerRequest) GetReadMarker() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadMarker
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	MemberIds     []string               `protobuf:"bytes,3,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_contract_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoomRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *CreateRoomRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RoomDetail            `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_contract_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRoomResponse) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Will produce RoomStateChangedResponse
type InviteRoomMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoomMemberRequest) Reset() {
	*x = InviteRoomMemberRequest{}
	mi := &file_contract_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomMemberRequest) ProtoMessage() {}

func (x *InviteRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{24}
}

func (x *InviteRoomMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteRoomMemberRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// Will produce RoomStateChangedResponse
type RemoveRoomMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MemberIds     []string               `protobuf:"bytes,2,rep,name=memberIds,proto3" json:"memberIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomMemberRequest) Reset() {
	*x = RemoveRoomMemberRequest{}
	mi := &file_contract_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomMemberRequest) ProtoMessage() {}

func (x *RemoveRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveRoomMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RemoveRoomMemberRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type RoomStateChangedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RoomDetail            `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateChangedResponse) Reset() {
	*x = RoomStateChangedResponse{}
	mi := &file_contract_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateChangedResponse) ProtoMessage() {}

func (x *RoomStateChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateChangedResponse.ProtoReflect.Descriptor instead.
func (*RoomStateChangedResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{26}
}

func (x *RoomStateChangedResponse) GetDetail() *RoomDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RoomEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RoomEventResponse_MessageEvent
	//	*RoomEventResponse_SystemEvent
	//	*RoomEventResponse_RoomStateChanged
	//	*RoomEventResponse_MessageEventReaction
	Payload       isRoomEventResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEventResponse) Reset() {
	*x = RoomEventResponse{}
	mi := &file_contract_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventResponse) ProtoMessage() {}

func (x *RoomEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventResponse.ProtoReflect.Descriptor instead.
func (*RoomEventResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{27}
}

func (x *RoomEventResponse) GetPayload() isRoomEventResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoomEventResponse) GetMessageEvent() *RoomEventMessageDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *RoomEventResponse) GetSystemEvent() *RoomEventSystemDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_SystemEvent); ok {
			return x.SystemEvent
		}
	}
	return nil
}

func (x *RoomEventResponse) GetRoomStateChanged() *RoomDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_RoomStateChanged); ok {
			return x.RoomStateChanged
		}
	}
	return nil
}

func (x *RoomEventResponse) GetMessageEventReaction() *RoomEventReactionDetail {
	if x != nil {
		if x, ok := x.Payload.(*RoomEventResponse_MessageEventReaction); ok {
			return x.MessageEventReaction
		}
	}
	return nil
}

type isRoomEventResponse_Payload interface {
	isRoomEventResponse_Payload()
}

type RoomEventResponse_MessageEvent struct {
	MessageEvent *RoomEventMessageDetail `protobuf:"bytes,1,opt,name=messageEvent,proto3,oneof"`
}

type RoomEventResponse_SystemEvent struct {
	SystemEvent *RoomEventSystemDetail `protobuf:"bytes,2,opt,name=systemEvent,proto3,oneof"`
}

type RoomEventResponse_RoomStateChanged struct {
	RoomStateChanged *RoomDetail `protobuf:"bytes,3,opt,name=roomStateChanged,proto3,oneof"`
}

type RoomEventResponse_MessageEventReaction struct {
	MessageEventReaction *RoomEventReactionDetail `protobuf:"bytes,5,opt,name=messageEventReaction,proto3,oneof"`
}

func (*RoomEventResponse_MessageEvent) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_SystemEvent) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_RoomStateChanged) isRoomEventResponse_Payload() {}

func (*RoomEventResponse_MessageEventReaction) isRoomEventResponse_Payload() {}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x1bru.sputnikn.api.contract.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fAuthUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"h\n" +
	"\n" +
	"UserDetail\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x00R\x06avatar\x88\x01\x01B\t\n" +
	"\a_avatar\"\xdc\x01\n" +
	"\x10AuthUserResponse\x12@\n" +
	"\x05error\x18\x01 \x01(\x0e2*.ru.sputnikn.api.contract.v1.AuthErrorTypeR\x05error\x12%\n" +
	"\vaccessToken\x18\x02 \x01(\tH\x00R\vaccessToken\x88\x01\x01\x12D\n" +
	"\x06detail\x18\x03 \x01(\v2'.ru.sputnikn.api.contract.v1.UserDetailH\x01R\x06detail\x88\x01\x01B\x0e\n" +
	"\f_accessTokenB\t\n" +
	"\a_detail\",\n" +
	"\x10ListRoomsRequest\x12\x18\n" +
	"\aroomIds\x18\x01 \x03(\tR\aroomIds\"\xa5\x02\n" +
	"\x10RoomMemberDetail\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1a\n" +
	"\bisOnline\x18\x03 \x01(\bR\bisOnline\x12U\n" +
	"\fmemberStatus\x18\x04 \x01(\x0e21.ru.sputnikn.api.contract.v1.RoomMemberStatusTypeR\fmemberStatus\x12\x1b\n" +
	"\x06avatar\x18\x05 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12B\n" +
	"\x0elastReadMarker\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReadMarkerB\t\n" +
	"\a_avatar\"\x9d\x02\n" +
	"\n" +
	"RoomDetail\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12G\n" +
	"\amembers\x18\x04 \x03(\v2-.ru.sputnikn.api.contract.v1.RoomMemberDetailR\amembers\x128\n" +
	"\x17eventMessageUnreadCount\x18\x05 \x01(\x05R\x17eventMessageUnreadCount\x126\n" +
	"\x16eventSystemUnreadCount\x18\x06 \x01(\x05R\x16eventSystemUnreadCountB\t\n" +
	"\a_avatar\"T\n" +
	"\x11ListRoomsResponse\x12?\n" +
	"\x06detail\x18\x01 \x03(\v2'.ru.sputnikn.api.contract.v1.RoomDetailR\x06detail\"\x92\x01\n" +
	"\x0fSinceTimeFilter\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12M\n" +
	"\torderType\x18\x02 \x01(\x0e2/.ru.sputnikn.api.contract.v1.SinceTimeOrderTypeR\torderType\"\xfb\x01\n" +
	"\x0eSyncRoomFilter\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12S\n" +
	"\vsinceFilter\x18\x02 \x01(\v2,.ru.sputnikn.api.contract.v1.SinceTimeFilterH\x00R\vsinceFilter\x88\x01\x01\x12L\n" +
	"\veventFilter\x18\x04 \x01(\x0e2*.ru.sputnikn.api.contract.v1.RoomEventTypeR\veventFilter\x12\x1e\n" +
	"\n" +
	"eventLimit\x18\x03 \x01(\x05R\n" +
	"eventLimitB\x0e\n" +
	"\f_sinceFilter\"_\n" +
	"\x10SyncRoomsRequest\x12K\n" +
	"\n" +
	"roomFilter\x18\x01 \x03(\v2+.ru.sputnikn.api.contract.v1.SyncRoomFilterR\n" +
	"roomFilter\"p\n" +
	"\x14ChatAttachmentDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\"\n" +
	"\fattachmentId\x18\x02 \x01(\tR\fattachmentId\x12\x1a\n" +
	"\bmimeType\x18\x03 \x01(\tR\bmimeType\"\xbb\x01\n" +
	"\x17RoomEventReactionDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb3\x03\n" +
	"\x16RoomEventMessageDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12Q\n" +
	"\n" +
	"attachment\x18\x05 \x03(\v21.ru.sputnikn.api.contract.v1.ChatAttachmentDetailR\n" +
	"attachment\x12P\n" +
	"\breaction\x18\x06 \x03(\v24.ru.sputnikn.api.contract.v1.RoomEventReactionDetailR\breaction\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb7\x01\n" +
	"\x15RoomEventSystemDetail\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc6\x01\n" +
	"\x11SyncRoomsResponse\x12Y\n" +
	"\rmessageEvents\x18\x01 \x03(\v23.ru.sputnikn.api.contract.v1.RoomEventMessageDetailR\rmessageEvents\x12V\n" +
	"\fsystemEvents\x18\x02 \x03(\v22.ru.sputnikn.api.contract.v1.RoomEventSystemDetailR\fsystemEvents\"\x85\x01\n" +
	"\x17RoomEventMessageRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1e\n" +
	"\n" +
	"attachment\x18\x02 \x03(\tR\n" +
	"attachment\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"g\n" +
	"\x18RoomEventMessageResponse\x12K\n" +
	"\x06detail\x18\x01 \x01(\v23.ru.sputnikn.api.contract.v1.RoomEventMessageDetailR\x06detail\"\xb1\x01\n" +
	"\x1fRoomEventMessageReactionRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12$\n" +
	"\rclientEventId\x18\x03 \x01(\x05R\rclientEventId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"p\n" +
	" RoomEventMessageReactionResponse\x12L\n" +
	"\x06detail\x18\x01 \x01(\v24.ru.sputnikn.api.contract.v1.RoomEventReactionDetailR\x06detail\"\x12\n" +
	"\x10ListUsersRequest\"R\n" +
	"\x11ListUsersResponse\x12=\n" +
	"\x05users\x18\x01 \x03(\v2'.ru.sputnikn.api.contract.v1.UserDetailR\x05users\"k\n" +
	"\x15RoomReadMarkerRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12:\n" +
	"\n" +
	"readMarker\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"readMarker\"o\n" +
	"\x11CreateRoomRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12\x1c\n" +
	"\tmemberIds\x18\x03 \x03(\tR\tmemberIdsB\t\n" +
	"\a_avatar\"U\n" +
	"\x12CreateRoomResponse\x12?\n" +
	"\x06detail\x18\x01 \x01(\v2'.ru.sputnikn.api.contract.v1.RoomDetailR\x06detail\"O\n" +
	"\x17InviteRoomMemberRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\tR\tmemberIds\"O\n" +
	"\x17RemoveRoomMemberRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1c\n" +
	"\tmemberIds\x18\x02 \x03(\tR\tmemberIds\"[\n" +
	"\x18RoomStateChangedResponse\x12?\n" +
	"\x06detail\x18\x01 \x01(\v2'.ru.sputnikn.api.contract.v1.RoomDetailR\x06detail\"\x94\x03\n" +
	"\x11RoomEventResponse\x12Y\n" +
	"\fmessageEvent\x18\x01 \x01(\v23.ru.sputnikn.api.contract.v1.RoomEventMessageDetailH\x00R\fmessageEvent\x12V\n" +
	"\vsystemEvent\x18\x02 \x01(\v22.ru.sputnikn.api.contract.v1.RoomEventSystemDetailH\x00R\vsystemEvent\x12U\n" +
	"\x10roomStateChanged\x18\x03 \x01(\v2'.ru.sputnikn.api.contract.v1.RoomDetailH\x00R\x10roomStateChanged\x12j\n" +
	"\x14messageEventReaction\x18\x05 \x01(\v24.ru.sputnikn.api.contract.v1.RoomEventReactionDetailH\x00R\x14messageEventReactionB\t\n" +
	"\apayload*G\n" +
	"\rAuthErrorType\x12\x15\n" +
	"\x11AuthErrorTypeNone\x10\x00\x12\x1f\n" +
	"\x1bAuthErrorTypeUserWrongCreds\x10\x01*\xb5\x01\n" +
	"\x14RoomMemberStatusType\x12\x1f\n" +
	"\x1bRoomMemberStatusTypeInvited\x10\x00\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeJoined\x10\x01\x12\x1c\n" +
	"\x18RoomMemberStatusTypeLeft\x10\x02\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeKicked\x10\x03\x12\x1e\n" +
	"\x1aRoomMemberStatusTypeBanned\x10\x04*X\n" +
	"\rRoomEventType\x12\x14\n" +
	"\x10roomEventTypeAll\x10\x00\x12\x18\n" +
	"\x14roomEventTypeMessage\x10\x01\x12\x17\n" +
	"\x13roomEventTypeSystem\x10\x02*P\n" +
	"\x12SinceTimeOrderType\x12\x1c\n" +
	"\x18sinceTimeOrderTypeNewest\x10\x00\x12\x1c\n" +
	"\x18sinceTimeOrderTypeOldest\x10\x012\xa3\n" +
	"\n" +
	"\vChatService\x12g\n" +
	"\bAuthUser\x12,.ru.sputnikn.api.contract.v1.AuthUserRequest\x1a-.ru.sputnikn.api.contract.v1.AuthUserResponse\x12j\n" +
	"\tListRooms\x12-.ru.sputnikn.api.contract.v1.ListRoomsRequest\x1a..ru.sputnikn.api.contract.v1.ListRoomsResponse\x12j\n" +
	"\tSyncRooms\x12-.ru.sputnikn.api.contract.v1.SyncRoomsRequest\x1a..ru.sputnikn.api.contract.v1.SyncRoomsResponse\x12j\n" +
	"\tListUsers\x12-.ru.sputnikn.api.contract.v1.ListUsersRequest\x1a..ru.sputnikn.api.contract.v1.ListUsersResponse\x12~\n" +
	"\x11SetRoomReadMarker\x122.ru.sputnikn.api.contract.v1.RoomReadMarkerRequest\x1a5.ru.sputnikn.api.contract.v1.RoomStateChangedResponse\x12m\n" +
	"\n" +
	"CreateRoom\x12..ru.sputnikn.api.contract.v1.CreateRoomRequest\x1a/.ru.sputnikn.api.contract.v1.CreateRoomResponse\x12\x7f\n" +
	"\x10InviteRoomMember\x124.ru.sputnikn.api.contract.v1.InviteRoomMemberRequest\x1a5.ru.sputnikn.api.contract.v1.RoomStateChangedResponse\x12\x7f\n" +
	"\x10RemoveRoomMember\x124.ru.sputnikn.api.contract.v1.RemoveRoomMemberRequest\x1a5.ru.sputnikn.api.contract.v1.RoomStateChangedResponse\x12}\n" +
	"\x0eAddRoomMessage\x124.ru.sputnikn.api.contract.v1.RoomEventMessageRequest\x1a5.ru.sputnikn.api.contract.v1.RoomEventMessageResponse\x12\x95\x01\n" +
	"\x16AddRoomMessageReaction\x12<.ru.sputnikn.api.contract.v1.RoomEventMessageReactionRequest\x1a=.ru.sputnikn.api.contract.v1.RoomEventMessageReactionResponse\x12_\n" +
	"\x13SubscribeRoomEvents\x12\x16.google.protobuf.Empty\x1a..ru.sputnikn.api.contract.v1.RoomEventResponse0\x01B\rZ\vcontract/v1b\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_contract_proto_goTypes = []any{
	(AuthErrorType)(0),                       // 0: ru.sputnikn.api.contract.v1.AuthErrorType
	(RoomMemberStatusType)(0),                // 1: ru.sputnikn.api.contract.v1.RoomMemberStatusType
	(RoomEventType)(0),                       // 2: ru.sputnikn.api.contract.v1.RoomEventType
	(SinceTimeOrderType)(0),                  // 3: ru.sputnikn.api.contract.v1.SinceTimeOrderType
	(*AuthUserRequest)(nil),                  // 4: ru.sputnikn.api.contract.v1.AuthUserRequest
	(*UserDetail)(nil),                       // 5: ru.sputnikn.api.contract.v1.UserDetail
	(*AuthUserResponse)(nil),                 // 6: ru.sputnikn.api.contract.v1.AuthUserResponse
	(*ListRoomsRequest)(nil),                 // 7: ru.sputnikn.api.contract.v1.ListRoomsRequest
	(*RoomMemberDetail)(nil),                 // 8: ru.sputnikn.api.contract.v1.RoomMemberDetail
	(*RoomDetail)(nil),                       // 9: ru.sputnikn.api.contract.v1.RoomDetail
	(*ListRoomsResponse)(nil),                // 10: ru.sputnikn.api.contract.v1.ListRoomsResponse
	(*SinceTimeFilter)(nil),                  // 11: ru.sputnikn.api.contract.v1.SinceTimeFilter
	(*SyncRoomFilter)(nil),                   // 12: ru.sputnikn.api.contract.v1.SyncRoomFilter
	(*SyncRoomsRequest)(nil),                 // 13: ru.sputnikn.api.contract.v1.SyncRoomsRequest
	(*ChatAttachmentDetail)(nil),             // 14: ru.sputnikn.api.contract.v1.ChatAttachmentDetail
	(*RoomEventReactionDetail)(nil),          // 15: ru.sputnikn.api.contract.v1.RoomEventReactionDetail
	(*RoomEventMessageDetail)(nil),           // 16: ru.sputnikn.api.contract.v1.RoomEventMessageDetail
	(*RoomEventSystemDetail)(nil),            // 17: ru.sputnikn.api.contract.v1.RoomEventSystemDetail
	(*SyncRoomsResponse)(nil),                // 18: ru.sputnikn.api.contract.v1.SyncRoomsResponse
	(*RoomEventMessageRequest)(nil),          // 19: ru.sputnikn.api.contract.v1.RoomEventMessageRequest
	(*RoomEventMessageResponse)(nil),         // 20: ru.sputnikn.api.contract.v1.RoomEventMessageResponse
	(*RoomEventMessageReactionRequest)(nil),  // 21: ru.sputnikn.api.contract.v1.RoomEventMessageReactionRequest
	(*RoomEventMessageReactionResponse)(nil), // 22: ru.sputnikn.api.contract.v1.RoomEventMessageReactionResponse
	(*ListUsersRequest)(nil),                 // 23: ru.sputnikn.api.contract.v1.ListUsersRequest
	(*ListUsersResponse)(nil),                // 24: ru.sputnikn.api.contract.v1.ListUsersResponse
	(*RoomReadMarkerRequest)(nil),            // 25: ru.sputnikn.api.contract.v1.RoomReadMarkerRequest
	(*CreateRoomRequest)(nil),                // 26: ru.sputnikn.api.contract.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),               // 27: ru.sputnikn.api.contract.v1.CreateRoomResponse
	(*InviteRoomMemberRequest)(nil),          // 28: ru.sputnikn.api.contract.v1.InviteRoomMemberRequest
	(*RemoveRoomMemberRequest)(nil),          // 29: ru.sputnikn.api.contract.v1.RemoveRoomMemberRequest
	(*RoomStateChangedResponse)(nil),         // 30: ru.sputnikn.api.contract.v1.RoomStateChangedResponse
	(*RoomEventResponse)(nil),                // 31: ru.sputnikn.api.contract.v1.RoomEventResponse
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 33: google.protobuf.Empty
}
var file_contract_proto_depIdxs = []int32{
	0,  // 0: ru.sputnikn.api.contract.v1.AuthUserResponse.error:type_name -> ru.sputnikn.api.contract.v1.AuthErrorType
	5,  // 1: ru.sputnikn.api.contract.v1.AuthUserResponse.detail:type_name -> ru.sputnikn.api.contract.v1.UserDetail
	1,  // 2: ru.sputnikn.api.contract.v1.RoomMemberDetail.memberStatus:type_name -> ru.sputnikn.api.contract.v1.RoomMemberStatusType
	32, // 3: ru.sputnikn.api.contract.v1.RoomMemberDetail.lastReadMarker:type_name -> google.protobuf.Timestamp
	8,  // 4: ru.sputnikn.api.contract.v1.RoomDetail.members:type_name -> ru.sputnikn.api.contract.v1.RoomMemberDetail
	9,  // 5: ru.sputnikn.api.contract.v1.ListRoomsResponse.detail:type_name -> ru.sputnikn.api.contract.v1.RoomDetail
	32, // 6: ru.sputnikn.api.contract.v1.SinceTimeFilter.since:type_name -> google.protobuf.Timestamp
	3,  // 7: ru.sputnikn.api.contract.v1.SinceTimeFilter.orderType:type_name -> ru.sputnikn.api.contract.v1.SinceTimeOrderType
	11, // 8: ru.sputnikn.api.contract.v1.SyncRoomFilter.sinceFilter:type_name -> ru.sputnikn.api.contract.v1.SinceTimeFilter
	2,  // 9: ru.sputnikn.api.contract.v1.SyncRoomFilter.eventFilter:type_name -> ru.sputnikn.api.contract.v1.RoomEventType
	12, // 10: ru.sputnikn.api.contract.v1.SyncRoomsRequest.roomFilter:type_name -> ru.sputnikn.api.contract.v1.SyncRoomFilter
	32, // 11: ru.sputnikn.api.contract.v1.RoomEventReactionDetail.createdAt:type_name -> google.protobuf.Timestamp
	14, // 12: ru.sputnikn.api.contract.v1.RoomEventMessageDetail.attachment:type_name -> ru.sputnikn.api.contract.v1.ChatAttachmentDetail
	15, // 13: ru.sputnikn.api.contract.v1.RoomEventMessageDetail.reaction:type_name -> ru.sputnikn.api.contract.v1.RoomEventReactionDetail
	32, // 14: ru.sputnikn.api.contract.v1.RoomEventMessageDetail.createdAt:type_name -> google.protobuf.Timestamp
	32, // 15: ru.sputnikn.api.contract.v1.RoomEventMessageDetail.updatedAt:type_name -> google.protobuf.Timestamp
	32, // 16: ru.sputnikn.api.contract.v1.RoomEventSystemDetail.createdAt:type_name -> google.protobuf.Timestamp
	16, // 17: ru.sputnikn.api.contract.v1.SyncRoomsResponse.messageEvents:type_name -> ru.sputnikn.api.contract.v1.RoomEventMessageDetail
	17, // 18: ru.sputnikn.api.contract.v1.SyncRoomsResponse.systemEvents:type_name -> ru.sputnikn.api.contract.v1.RoomEventSystemDetail
	16, // 19: ru.sputnikn.api.contract.v1.RoomEventMessageResponse.detail:type_name -> ru.sputnikn.api.contract.v1.RoomEventMessageDetail
	15, // 20: ru.sputnikn.api.contract.v1.RoomEventMessageReactionResponse.detail:type_name -> ru.sputnikn.api.contract.v1.RoomEventReactionDetail
	5,  // 21: ru.sputnikn.api.contract.v1.ListUsersResponse.users:type_name -> ru.sputnikn.api.contract.v1.UserDetail
	32, // 22: ru.sputnikn.api.contract.v1.RoomReadMarkerRequest.readMarker:type_name -> google.protobuf.Timestamp
	9,  // 23: ru.sputnikn.api.contract.v1.CreateRoomResponse.detail:type_name -> ru.sputnikn.api.contract.v1.RoomDetail
	9,  // 24: ru.sputnikn.api.contract.v1.RoomStateChangedResponse.detail:type_name -> ru.sputnikn.api.contract.v1.RoomDetail
	16, // 25: ru.sputnikn.api.contract.v1.RoomEventResponse.messageEvent:type_name -> ru.sputnikn.api.contract.v1.RoomEventMessageDetail
	17, // 26: ru.sputnikn.api.contract.v1.RoomEventResponse.systemEvent:type_name -> ru.sputnikn.api.contract.v1.RoomEventSystemDetail
	9,  // 27: ru.sputnikn.api.contract.v1.RoomEventResponse.roomStateChanged:type_name -> ru.sputnikn.api.contract.v1.RoomDetail
	15, // 28: ru.sputnikn.api.contract.v1.RoomEventResponse.messageEventReaction:type_name -> ru.sputnikn.api.contract.v1.RoomEventReactionDetail
	4,  // 29: ru.sputnikn.api.contract.v1.ChatService.AuthUser:input_type -> ru.sputnikn.api.contract.v1.AuthUserRequest
	7,  // 30: ru.sputnikn.api.contract.v1.ChatService.ListRooms:input_type -> ru.sputnikn.api.contract.v1.ListRoomsRequest
	13, // 31: ru.sputnikn.api.contract.v1.ChatService.SyncRooms:input_type -> ru.sputnikn.api.contract.v1.SyncRoomsRequest
	23, // 32: ru.sputnikn.api.contract.v1.ChatService.ListUsers:input_type -> ru.sputnikn.api.contract.v1.ListUsersRequest
	25, // 33: ru.sputnikn.api.contract.v1.ChatService.SetRoomReadMarker:input_type -> ru.sputnikn.api.contract.v1.RoomReadMarkerRequest
	26, // 34: ru.sputnikn.api.contract.v1.ChatService.CreateRoom:input_type -> ru.sputnikn.api.contract.v1.CreateRoomRequest
	28, // 35: ru.sputnikn.api.contract.v1.ChatService.InviteRoomMember:input_type -> ru.sputnikn.api.contract.v1.InviteRoomMemberRequest
	29, // 36: ru.sputnikn.api.contract.v1.ChatService.RemoveRoomMember:input_type -> ru.sputnikn.api.contract.v1.RemoveRoomMemberRequest
	19, // 37: ru.sputnikn.api.contract.v1.ChatService.AddRoomMessage:input_type -> ru.sputnikn.api.contract.v1.RoomEventMessageRequest
	21, // 38: ru.sputnikn.api.contract.v1.ChatService.AddRoomMessageReaction:input_type -> ru.sputnikn.api.contract.v1.RoomEventMessageReactionRequest
	33, // 39: ru.sputnikn.api.contract.v1.ChatService.SubscribeRoomEvents:input_type -> google.protobuf.Empty
	6,  // 40: ru.sputnikn.api.contract.v1.ChatService.AuthUser:output_type -> ru.sputnikn.api.contract.v1.AuthUserResponse
	10, // 41: ru.sputnikn.api.contract.v1.ChatService.ListRooms:output_type -> ru.sputnikn.api.contract.v1.ListRoomsResponse
	18, // 42: ru.sputnikn.api.contract.v1.ChatService.SyncRooms:output_type -> ru.sputnikn.api.contract.v1.SyncRoomsResponse
	24, // 43: ru.sputnikn.api.contract.v1.ChatService.ListUsers:output_type -> ru.sputnikn.api.contract.v1.ListUsersResponse
	30, // 44: ru.sputnikn.api.contract.v1.ChatService.SetRoomReadMarker:output_type -> ru.sputnikn.api.contract.v1.RoomStateChangedResponse
	27, // 45: ru.sputnikn.api.contract.v1.ChatService.CreateRoom:output_type -> ru.sputnikn.api.contract.v1.CreateRoomResponse
	30, // 46: ru.sputnikn.api.contract.v1.ChatService.InviteRoomMember:output_type -> ru.sputnikn.api.contract.v1.RoomStateChangedResponse
	30, // 47: ru.sputnikn.api.contract.v1.ChatService.RemoveRoomMember:output_type -> ru.sputnikn.api.contract.v1.RoomStateChangedResponse
	20, // 48: ru.sputnikn.api.contract.v1.ChatService.AddRoomMessage:output_type -> ru.sputnikn.api.contract.v1.RoomEventMessageResponse
	22, // 49: ru.sputnikn.api.contract.v1.ChatService.AddRoomMessageReaction:output_type -> ru.sputnikn.api.contract.v1.RoomEventMessageReactionResponse
	31, // 50: ru.sputnikn.api.contract.v1.ChatService.SubscribeRoomEvents:output_type -> ru.sputnikn.api.contract.v1.RoomEventResponse
	40, // [40:51] is the sub-list for method output_type
	29, // [29:40] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	file_contract_proto_msgTypes[1].OneofWrappers = []any{}
	file_contract_proto_msgTypes[2].OneofWrappers = []any{}
	file_contract_proto_msgTypes[4].OneofWrappers = []any{}
	file_contract_proto_msgTypes[5].OneofWrappers = []any{}
	file_contract_proto_msgTypes[8].OneofWrappers = []any{}
	file_contract_proto_msgTypes[22].OneofWrappers = []any{}
	file_contract_proto_msgTypes[27].OneofWrappers = []any{
		(*RoomEventResponse_MessageEvent)(nil),
		(*RoomEventResponse_SystemEvent)(nil),
		(*RoomEventResponse_RoomStateChanged)(nil),
		(*RoomEventResponse_MessageEventReaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		EnumInfos:         file_contract_proto_enumTypes,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
